// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Admin_Remix.Models;

namespace Proyecto_Admin_Remix.Migrations.Formularios
{
    [DbContext(typeof(FormulariosContext))]
    [Migration("20201124010542_formulario")]
    partial class formulario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Proyecto_Admin_Remix.Models.Formularios", b =>
                {
                    b.Property<int>("FormularioID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Cedula")
                        .HasColumnType("int");

                    b.Property<string>("Estado_civil")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Fech_Naciemento")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<int>("celular")
                        .HasColumnType("int");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<int>("telefono")
                        .HasColumnType("int");

                    b.HasKey("FormularioID");

                    b.ToTable("FormulariosEN");
                });
#pragma warning restore 612, 618
        }
    }
}
